name: SLSA Provenance

on:
  release:
    types: [created]

jobs:
  provenance:
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.9.0
    with:
      artifact_path: ./bin/
